### ISSUE TITLE
[Task-4] Create Simple PKI using SQLite and Populate with Sample Data

### ISSUE THREAD

**Issue by JaWitold** [JaWitold/Software-Engineering-Lab-in-Cybersecurity#5]
**Task Description**
Objective: Develop a simple Public Key Infrastructure (PKI) system using SQLite to store and manage private keys. This system should be capable of handling basic PKI functionalities and should be pre-populated with sample data for testing and demonstration purposes.

**Requirements:**

**1. SQLite Database Setup:**
    Design and set up an SQLite database to store PKI-related data. This database should have a table for storing private keys along with associated metadata (e.g., key ID, creation date, owner information).
Ensure the database schema is well-designed, considering aspects like data types, constraints, and indexes for efficient data retrieval.

**2. Data Model and Storage Mechanism:**
    Define a data model that clearly represents the entities and their relationships within the PKI system.
Implement a secure storage mechanism for private keys. This includes considerations for encryption and access controls to ensure that the keys are securely stored and protected against unauthorized access.

**3. Sample Data Population:**
    Create a script or a set of scripts to populate the database with sample data. This data should include a variety of private keys and associated metadata to adequately demonstrate the system's capabilities.
    Ensure that the sample data is representative of real-world use cases but does not contain any sensitive or personal information.

**Comment by Komitus** [comment]
https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/tree/mateusz.checinski/task-4

The name should be public key.
Also remember public keys consists of two uints.
Maybe we can use sql mapping like in alchemy? (see example https://github.com/Komitus/Secure-Cloud-Computing/blob/master/db_model.py)? If we are going to make server from our code, then maybe referred earlier flask?
Before inserting public key to the db, we should check if user really is possessing corresponding private key to protect against attacks connected to inserting such keys.

**Comment by JaWitold** [comment]
@Cheta2000 did you prepared pull Request ?
