### ISSUE TITLE
在src文件中没有main.py文件

### ISSUE THREAD

**Issue by gting1** [JaWitold/Software-Engineering-Lab-in-Cybersecurity#53]
在运行python文件时执行src文件中的哪个.py文件

**Comment by JaWitold** [comment]
hi,
application have 2 entrypoints specified in https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/blob/main-v2/setup.cfg file

> console_scripts =
>     deploy-contract = software_engineering_lab_in_cybersecurity.deployment.cli:run
>     client = software_engineering_lab_in_cybersecurity.client.cli:run

should be available in your venv, otherwise try building with `tox -e build`  _deploy-contract_ and _client_  programs are available

**Comment by gting1** [comment]
必须在venv环境中使用吗

**Comment by JaWitold** [comment]
@gting1 ![image](https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/47141012/1c6e36ee-4ea8-4c04-ae70-e0d9f1f755a6)
executed from project root directory

**Comment by gting1** [comment]
(venv) gt@gt-virtual-machine:~/Software-Engineering-Lab-in-Cybersecurity$ python src/software_engineering_lab_in_cybersecurity/client/cli.py
[2024-03-12 16:59:51] ERROR:__main__:No operation specified. Use --sign <message> to sign or --verify to verify.
(venv) gt@gt-virtual-machine:~/Software-Engineering-Lab-in-Cybersecurity$ python src/software_engineering_lab_in_cybersecurity/deployment/cli.py
[2024-03-12 17:11:17] ERROR:__main__:accounts.json file not found.
这个是编译的两个入口点的cli.py文件，出现了上述两个问题，我是在Ubuntu虚拟机中跑的这个实验

**Comment by JaWitold** [comment]
First to understand purpose of this file: it is generated by Ganache test network to simulate PKI which we did in simplest form -  exporting Ganache generated accounts and adresses 

Have you started docker container with ganache? I belive that should generate accounts.json file 
![image](https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/47141012/f38ab208-50eb-4554-b7e5-8567d99cde9b)
the content of this file would be generated based on wallet.mnemonic and should look like ``` json {
  "addresses": {
    "0x297875a2f7d2c9bd9e06b2ef26ff39d2aa51f498": "0x297875a2f7d2c9bd9e06b2ef26ff39d2aa51f498",
    "0xad37f4a148a0d318d3755152ad64e241bf2bccca": "0xad37f4a148a0d318d3755152ad64e241bf2bccca",
    "0xcd256e2d6e7e560c6bec98e9c0e694f58d0ef316": "0xcd256e2d6e7e560c6bec98e9c0e694f58d0ef316",
    "0x22847384ee5aa695f2a7696b171ba9f2e38f7c4e": "0x22847384ee5aa695f2a7696b171ba9f2e38f7c4e",
    "0xaa7ed5607c30c458d56e31a864e52ab7ff652a04": "0xaa7ed5607c30c458d56e31a864e52ab7ff652a04",
    "0x270a11e0766b9aeb8044447868ecf14267be5689": "0x270a11e0766b9aeb8044447868ecf14267be5689",
    "0xddd8303435676bb1b2fd357e506754aaa8260b8f": "0xddd8303435676bb1b2fd357e506754aaa8260b8f",
    "0xfd15bdbd83d62110b6367fd7ec89fa5de50a4559": "0xfd15bdbd83d62110b6367fd7ec89fa5de50a4559",
    "0x0569a8b086a34d3cec9bdc5e277b3fd8b60cf57d": "0x0569a8b086a34d3cec9bdc5e277b3fd8b60cf57d",
    "0xd889f5dbf8ff7012f8c46a0298e2f78691bc12ae": "0xd889f5dbf8ff7012f8c46a0298e2f78691bc12ae"
  },
  "private_keys": {
    "0x297875a2f7d2c9bd9e06b2ef26ff39d2aa51f498": "0x385ae368172d413be0f259bc09e5e41a8f73137e0c50fee3e528309eb0bef156",
    "0xad37f4a148a0d318d3755152ad64e241bf2bccca": "0xd5af1c6b8a5bd1cd236487461bc40ef9768ba22d7e53b2c15bc9ac7a8442fe31",
    "0xcd256e2d6e7e560c6bec98e9c0e694f58d0ef316": "0xc1a7bed930fa03f427f1e047603bb41a36b112aa4831242890c7152b902de490",
    "0x22847384ee5aa695f2a7696b171ba9f2e38f7c4e": "0x71a8e536e9a078781d52b3b81303e89d25372ac799f69dde52e80bacfed2153f",
    "0xaa7ed5607c30c458d56e31a864e52ab7ff652a04": "0x9ab0846b1100fb07b80da569038be38f4aff90ae7ed94586446d745f94ca2415",
    "0x270a11e0766b9aeb8044447868ecf14267be5689": "0xcbd50b15ddf0bf6f40eb304170a091034256f33aec56475f618fbf1b08a5c8ee",
    "0xddd8303435676bb1b2fd357e506754aaa8260b8f": "0xd7bcdc380647c342a7905bb3528184e842271d06191c59bb32bb2506b12a340a",
    "0xfd15bdbd83d62110b6367fd7ec89fa5de50a4559": "0x322950d9b3bdd3b8ec57a52968497584d660799192b104f2118e53fb6bdd2b52",
    "0x0569a8b086a34d3cec9bdc5e277b3fd8b60cf57d": "0xe452859840fb0b29935379c7b5d7e2ce751c96907b80b98ce8e716bf3c46990a",
    "0xd889f5dbf8ff7012f8c46a0298e2f78691bc12ae": "0x878702def27d99384f2f3039502232fcc58e50a8c3171941399a89790783df58"
  }
}```

**Comment by gting1** [comment]
好的，现在在拉取 Ganache Docker 镜像时出现了问题

**Comment by gting1** [comment]
<img width="909" alt="微信图片_20240313214337" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/b4bd0f50-a968-4020-8e98-fd1c0930fe57">
如图所示已经用ganache启动了docker容器，但是仍然出现上述错误，没有生成account.json文件

**Comment by JaWitold** [comment]
`docker compose up -d  --build` - there is preconfigurted compose.yaml file and dockerfile

**Comment by gting1** [comment]
<img width="944" alt="微信图片_20240314095802" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/88c9f01c-4066-4a3e-8e8c-58e866ae2253">
<img width="944" alt="微信图片_20240314095845" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/327d218d-9b5f-442e-889e-0a124dbecaf1">
执行上述命令docker compose up -d  --build出现这个错误，也下载了build-essential这个包

**Comment by JaWitold** [comment]
try building the image with `--no-cache` flag

``` bash
docker compose build --no-cache && docker compose up -d
```

https://askubuntu.com/questions/1028396/installing-build-essential-fails-in-docker

**Comment by gting1** [comment]
<img width="933" alt="微信图片_20240314204153" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/57fb0736-e659-4544-8c57-e20275db8f1d">
还是一样的问题

**Comment by JaWitold** [comment]
https://stackoverflow.com/questions/61567404/docker-temporary-failure-resolving-deb-debian-org You can also try removing all current docker images and then build it again, it might be also something with your network setup - it states that it is not able to find debian repositories. Another way you could try is to setup Ganache locally instead of on docker (check on Ganache github page)

**Comment by gting1** [comment]
<img width="934" alt="1710731082717" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/c342affb-4be2-4362-b21a-f526ecb77704">
通过ganache-cli已经开启了以太坊，但是错误信息显示无法连接到

**Comment by JaWitold** [comment]
it looks like you havent set all necessary data to connect to ganache network, load ip address, port, chain_id either from .env (.env.example) or by setting CLI arguments (src/software_engineering_lab_in_cybersecurity/utility.py)

**Comment by gting1** [comment]
<img width="932" alt="1710748752496" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/062cb941-edb3-4b43-ad9d-df11b82dafdc">
还是无法连接到，加载.env文件也是

**Comment by JaWitold** [comment]
1. wrong parameter names - check them here: https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/issues/53#issuecomment-1991407600 using --help
2. wrong usage - do not call utility.py file
`deploy-contract --ip 127.0.0.1 --chain-id 1337 ...`

**Comment by gting1** [comment]
<img width="890" alt="1710766532542" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/774c39ce-101a-4c47-b227-27e4d39c2c2b">
re.escape期望的输入是一个字符串或字节序列，但它获得的是None

**Comment by JaWitold** [comment]
You didnt specified name of contract you want to deploy 
by .env file https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/blob/6b95ecb48cf1dbd349e89e839c6cbba3d8631456/.env.example#L13
or by CLI argument https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/blob/6b95ecb48cf1dbd349e89e839c6cbba3d8631456/src/software_engineering_lab_in_cybersecurity/deployment/cli.py#L38

**Comment by gting1** [comment]
<img width="941" alt="1710856353742" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/b55d3548-03ed-4fff-8f6a-5f4b2eed13d1">
<img width="941" alt="1710856437452" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/d53b696b-d7c9-4aaf-9e10-d26fe9c45e05">
zhe'l这两个命令都是在部署智能合约，为什么这样

**Comment by JaWitold** [comment]
looks like ganache error - check out its documentation

**Comment by gting1** [comment]
<img width="755" alt="1710904061563" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/a62f0b23-34bb-4acb-9c93-b5d28c73d604">


这次试着使用ganache客户端布置了节点  使用命令行部署智能合约还是出现上述情况

**Comment by gting1** [comment]
![Uploading 微信图片_20240320161410.png…]()

**Comment by gting1** [comment]
<img width="941" alt="微信图片_20240320161748" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/90b4a53d-9f63-40de-8c8d-4566bc87d60e">
<img width="935" alt="微信图片_20240320161805" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/4944b953-2e70-4fe4-ac25-fa70333eb57b">
这个是为什么呢

**Comment by JaWitold** [comment]
try another hostname: https://archive.trufflesuite.com/docs/ganache/how-to/work-with-filecoin/get-started-with-the-gui/#configuration

https://stackoverflow.com/questions/73224954/ganache-doesnt-connect-to-the-network

**Comment by gting1** [comment]
<img width="537" alt="1710925605148" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/7de0b605-fb5d-4de4-89d6-66805159838a">
ganache中的账户与上述账户不同是正确的吗

**Comment by JaWitold** [comment]
thats are from ganache, but from accounts.json - if you are running on docker This file is created by ganache and matches ganache accounts. seeing it does not indicate that python script has connected to ganache network

**Comment by gting1** [comment]
那这个原因是什么呢  docker compose up -d  --build的问题吗

**Comment by JaWitold** [comment]
are you started it from docker compose instead of this client

> <img alt="1710904061563" width="755" src="https://private-user-images.githubusercontent.com/121794754/314367913-a62f0b23-34bb-4acb-9c93-b5d28c73d604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjQ2NzIsIm5iZiI6MTcxMDkyNDM3MiwicGF0aCI6Ii8xMjE3OTQ3NTQvMzE0MzY3OTEzLWE2MmYwYjIzLTM0YmItNGFjYi05YzkzLWI1ZDI4YzczZDYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwODQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzI2NDgzNDYzM2ZhODY5YjA5ZGVmM2JkYTgxNjA2YjZjNTA1OWMwNzU4OTdmMmE4YzJmZTY2MzA2MmUzZDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y_BY-rYaPY4EFgzaEUUl4cFpCNwlTIkGsMVUnaABDdw">
> 这次试着使用ganache客户端布置了节点 使用命令行部署智能合约还是出现上述情况

**Comment by gting1** [comment]
是的  先使用docker命令得到的account文件



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月20日 17:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [JaWitold/Software-Engineering-Lab-in-Cybersecurity] 在src文件中没有main.py文件 (Issue #53) |

are you started it from docker compose instead of this client

这次试着使用ganache客户端布置了节点 使用命令行部署智能合约还是出现上述情况

**Comment by JaWitold** [comment]
are the account.json account addresses match ganache addresses?

**Comment by gting1** [comment]
并不相关



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月20日 18:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [JaWitold/Software-Engineering-Lab-in-Cybersecurity] 在src文件中没有main.py文件 (Issue #53) |

are the account.json account addresses match ganache addresses?

**Comment by gting1** [comment]
<img width="940" alt="1710988663307" src="https://github.com/JaWitold/Software-Engineering-Lab-in-Cybersecurity/assets/121794754/d51e9cc5-e9cd-421a-bd9d-f3f95f47393b">
如何使ganache中的account与account.json文件中的account一致

**Comment by gting1** [comment]
account.json文件由docker compose up -d --build
该命令获得

**Comment by JaWitold** [comment]
and the blockchain must be run on docker to utilize this accounts, not in separate standalone Ganache
